# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/fabian/Dokumente/Informatik/Python-Programme/eigene_programme/chakra_easy_config/chakrafastconfig.ui'
#
# Created: Sat Jan 21 14:04:45 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(633, 599)
        MainWindow.setAcceptDrops(False)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(200, 100))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_codc = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_codc.setTitle(QtGui.QApplication.translate("MainWindow", "Chakra codec", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_codc.setObjectName(_fromUtf8("groupBox_codc"))
        self.checkBox_codec = QtGui.QCheckBox(self.groupBox_codc)
        self.checkBox_codec.setGeometry(QtCore.QRect(31, 57, 59, 21))
        self.checkBox_codec.setText(QtGui.QApplication.translate("MainWindow", "Codec", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_codec.setObjectName(_fromUtf8("checkBox_codec"))
        self.checkBox_flash = QtGui.QCheckBox(self.groupBox_codc)
        self.checkBox_flash.setGeometry(QtCore.QRect(31, 98, 54, 21))
        self.checkBox_flash.setText(QtGui.QApplication.translate("MainWindow", "Flash", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_flash.setObjectName(_fromUtf8("checkBox_flash"))
        self.pushButton_codec = QtGui.QPushButton(self.groupBox_codc)
        self.pushButton_codec.setGeometry(QtCore.QRect(30, 150, 63, 23))
        self.pushButton_codec.setFocusPolicy(QtCore.Qt.TabFocus)
        self.pushButton_codec.setText(QtGui.QApplication.translate("MainWindow", "Install ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_codec.setObjectName(_fromUtf8("pushButton_codec"))
        self.gridLayout_2.addWidget(self.groupBox_codc, 0, 0, 1, 1)
        self.groupBox_fonts = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_fonts.setTitle(QtGui.QApplication.translate("MainWindow", "Chakra fonts", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_fonts.setObjectName(_fromUtf8("groupBox_fonts"))
        self.groupBox_locale_2 = QtGui.QGroupBox(self.groupBox_fonts)
        self.groupBox_locale_2.setGeometry(QtCore.QRect(-163, 0, 159, 295))
        self.groupBox_locale_2.setTitle(QtGui.QApplication.translate("MainWindow", "Chakra locale", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_locale_2.setObjectName(_fromUtf8("groupBox_locale_2"))
        self.layoutWidget_2 = QtGui.QWidget(self.groupBox_locale_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 40, 131, 141))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox_9 = QtGui.QGroupBox(self.layoutWidget_2)
        self.groupBox_9.setTitle(QtGui.QApplication.translate("MainWindow", "Language system", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.comboBox_2 = QtGui.QComboBox(self.groupBox_9)
        self.comboBox_2.setGeometry(QtCore.QRect(20, 30, 85, 23))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.setItemText(0, QtGui.QApplication.translate("MainWindow", "New element?", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_7.addWidget(self.groupBox_9)
        self.pushButton_locale_2 = QtGui.QPushButton(self.layoutWidget_2)
        self.pushButton_locale_2.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_locale_2.setObjectName(_fromUtf8("pushButton_locale_2"))
        self.verticalLayout_7.addWidget(self.pushButton_locale_2)
        self.pushButton_fonts = QtGui.QPushButton(self.groupBox_fonts)
        self.pushButton_fonts.setGeometry(QtCore.QRect(40, 200, 63, 23))
        self.pushButton_fonts.setText(QtGui.QApplication.translate("MainWindow", "Install ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_fonts.setObjectName(_fromUtf8("pushButton_fonts"))
        self.checkBox_oxygen = QtGui.QCheckBox(self.groupBox_fonts)
        self.checkBox_oxygen.setGeometry(QtCore.QRect(20, 140, 93, 21))
        self.checkBox_oxygen.setText(QtGui.QApplication.translate("MainWindow", "oxygen fonts", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_oxygen.setObjectName(_fromUtf8("checkBox_oxygen"))
        self.checkBox_ubuntu = QtGui.QCheckBox(self.groupBox_fonts)
        self.checkBox_ubuntu.setGeometry(QtCore.QRect(20, 50, 95, 21))
        self.checkBox_ubuntu.setText(QtGui.QApplication.translate("MainWindow", "Ubuntu fonts", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_ubuntu.setObjectName(_fromUtf8("checkBox_ubuntu"))
        self.checkBox_ms = QtGui.QCheckBox(self.groupBox_fonts)
        self.checkBox_ms.setGeometry(QtCore.QRect(20, 100, 72, 21))
        self.checkBox_ms.setText(QtGui.QApplication.translate("MainWindow", "ms fonts", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_ms.setObjectName(_fromUtf8("checkBox_ms"))
        self.gridLayout_2.addWidget(self.groupBox_fonts, 0, 2, 1, 1)
        self.groupBox_repo = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_repo.setTitle(QtGui.QApplication.translate("MainWindow", "Chakra repo config", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_repo.setObjectName(_fromUtf8("groupBox_repo"))
        self.checkBox_unstable = QtGui.QCheckBox(self.groupBox_repo)
        self.checkBox_unstable.setGeometry(QtCore.QRect(11, 147, 73, 21))
        self.checkBox_unstable.setText(QtGui.QApplication.translate("MainWindow", "unstable", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_unstable.setObjectName(_fromUtf8("checkBox_unstable"))
        self.checkBox_ccr = QtGui.QCheckBox(self.groupBox_repo)
        self.checkBox_ccr.setGeometry(QtCore.QRect(11, 53, 41, 21))
        self.checkBox_ccr.setText(QtGui.QApplication.translate("MainWindow", "ccr", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_ccr.setObjectName(_fromUtf8("checkBox_ccr"))
        self.checkBox_testing = QtGui.QCheckBox(self.groupBox_repo)
        self.checkBox_testing.setGeometry(QtCore.QRect(11, 100, 63, 21))
        self.checkBox_testing.setText(QtGui.QApplication.translate("MainWindow", "testing", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_testing.setObjectName(_fromUtf8("checkBox_testing"))
        self.pushButton_repo = QtGui.QPushButton(self.groupBox_repo)
        self.pushButton_repo.setGeometry(QtCore.QRect(30, 200, 61, 23))
        self.pushButton_repo.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_repo.setObjectName(_fromUtf8("pushButton_repo"))
        self.gridLayout_2.addWidget(self.groupBox_repo, 0, 3, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MainWindow", "Install application", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_6)
        self.groupBox_8.setGeometry(QtCore.QRect(331, 20, 311, 157))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("MainWindow", " QT install", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.scrollArea_2 = QtGui.QScrollArea(self.groupBox_8)
        self.scrollArea_2.setGeometry(QtCore.QRect(20, 30, 261, 211))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 255, 205))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.pushButton_6 = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_6.setGeometry(QtCore.QRect(360, 200, 91, 23))
        self.pushButton_6.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.pushButton_7 = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_7.setGeometry(QtCore.QRect(500, 200, 91, 23))
        self.pushButton_7.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_6)
        self.groupBox_7.setGeometry(QtCore.QRect(11, 19, 321, 157))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("MainWindow", "Bundle install", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.scrollArea = QtGui.QScrollArea(self.groupBox_7)
        self.scrollArea.setGeometry(QtCore.QRect(20, 30, 281, 211))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 275, 205))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pushButton_5 = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_5.setGeometry(QtCore.QRect(40, 200, 111, 23))
        self.pushButton_5.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.pushButton_8 = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_8.setGeometry(QtCore.QRect(192, 200, 121, 23))
        self.pushButton_8.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout_2.addWidget(self.groupBox_6, 1, 0, 1, 4)
        self.groupBox_locale = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_locale.setTitle(QtGui.QApplication.translate("MainWindow", "Chakra locale", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_locale.setObjectName(_fromUtf8("groupBox_locale"))
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_locale)
        self.groupBox_5.setGeometry(QtCore.QRect(11, 41, 129, 112))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "Language system", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.comboBox = QtGui.QComboBox(self.groupBox_5)
        self.comboBox.setGeometry(QtCore.QRect(20, 30, 85, 23))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "New element?", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_locale = QtGui.QPushButton(self.groupBox_locale)
        self.pushButton_locale.setGeometry(QtCore.QRect(50, 170, 52, 23))
        self.pushButton_locale.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_locale.setObjectName(_fromUtf8("pushButton_locale"))
        self.gridLayout_2.addWidget(self.groupBox_locale, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        pass


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

